# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: xf

before:
  hooks:
    - go mod tidy

builds:
  - id: xf
    binary: bin/xf
    main: ./cmd/xf
    mod_timestamp: "{{.CommitTimestamp}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/xenforo-ltd/cli/internal/version.Version=v{{.Version}}
      - -X github.com/xenforo-ltd/cli/internal/version.Commit={{.ShortCommit}}
      - -X github.com/xenforo-ltd/cli/internal/version.Date={{.CommitDate}}

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

notarize:
  macos:
    - enabled: "{{ isEnvSet \"MACOS_SIGN_P12\" }}"

      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"

      notarize:
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"

archives:
  - formats: [ tar.gz ]
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS_
      {{- else }}{{ .Os }}_{{ end }}
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        formats: [ zip ]

release:
  prerelease: auto
  name_template: "XenForo CLI v{{.Version}}"

homebrew_casks:
  - name: xf-cli
    description: "Command line interface for XenForo"
    homepage: "https://github.com/xenforo-ltd/cli"

    binaries:
      - bin/xf

    # generate_completions_from_executable:
    #   shell_parameter_format: cobra
    #   args:
    #     - completion
    #   shells:
    #     - bash
    #     - zsh
    #     - fish
    #     - pwsh

    zap:
      trash:
        - "~/Library/Application Support/xf/"
        - "~/.config/xf/"
      delete:
        - "~/Library/Caches/xf/"
        - "~/.cache/xf/"

    # skip_upload: auto
    commit_msg_template: "XenForo CLI: v{{.Version}}"

    repository:
      owner: xenforo-ltd
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN_GORELEASER }}"

    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com

winget:
  - name: xf-cli
    package_identifier: XenForo.CLI
    package_name: "XenForo CLI"
    short_description: "Command line interface for XenForo"
    homepage: "https://github.com/xenforo-ltd/cli"
    license: "mit"
    license_url: "https://github.com/xenforo-ltd/cli/blob/main/LICENSE"
    release_notes_url: "https://github.com/xenforo-ltd/cli/releases/tag/{{.Tag}}"
    publisher: XenForo Ltd.
    publisher_url: https://xenforo.com
    publisher_support_url: "https://github.com/xenforo-ltd/cli/issues/new"
    privacy_url: "http://xenforo.com/privacy-policy/"

    tags:
      - xenforo

    # skip_upload: auto
    commit_msg_template: "XenForo CLI: v{{.Version}}"

    installation_notes: "Information on how to install. Can also be a URL"

    repository:
      owner: xenforo-ltd
      name: winget-pkgs
      token: "{{ .Env.GITHUB_TOKEN_GORELEASER }}"
      branch: "{{.ProjectName}}-{{.Version}}"
      # pull_request:
      #   enabled: true
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master

    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com
