[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""

body = """
{%- macro remote_url() -%}
	https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro print_commit(commit) -%}
	- {% if commit.scope -%}*({{ commit.scope }})* {% endif -%}
		{% if commit.breaking -%}**Breaking**: {% endif -%}
		{{ commit.message | split(pat="\n") | first | upper_first | trim }}
{%- endmacro -%}

{%- if version %}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
    ## [Unreleased]
{% endif -%}

{%- for group, commits in commits | group_by(attribute="group") %}
	### {{ group | striptags | trim | upper_first }}

    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") -%}
        {{ self::print_commit(commit=commit) }}
    {% endfor -%}
    {% for commit in commits -%}
        {% if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
"""

footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- for release in releases %}
    {%- if release.version %}
        {%- if release.previous.version %}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/compare/{{ release.previous.version }}..{{ release.version }}
        {%- else %}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/tree/{{ release.version }}
        {%- endif -%}
    {%- else %}
        [Unreleased]: \
			{{ self::remote_url() }}/compare/{{ release.previous.version }}..HEAD
    {%- endif -%}
{% endfor -%}
"""

[git]
filter_unconventional = false
fail_on_unmatched_commit = true

commit_preprocessors = [{ pattern = '\(#([0-9]+)\)', replace = "" }]

commit_parsers = [
	{ message = "^feat", group = "<!-- 0 -->Features" },
	{ message = "^fix", group = "<!-- 10 -->Bug fixes" },
	{ message = "^refactor", group = "<!-- 20 -->Refactor" },
	{ message = "^docs", group = "<!-- 30 -->Documentation" },
	{ message = "^perf", group = "<!-- 40 -->Performance" },
	{ message = "^style", group = "<!-- 50 -->Style" },
	{ message = "^test", group = "<!-- 60 -->Tests" },
	{ message = "^build", group = "<!-- 70 -->Build" },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(release.*\\)", skip = true },
	{ message = "^chore|^ci", group = "<!-- 80 -->Miscellaneous" },
	{ message = "^revert", group = "<!-- 90 -->Revert" },
	{ message = "^.*", group = "<!-- 99 -->Other" },
]

[remote.github]
owner = "xenforo-ltd"
repo = "cli"
