services:
  xf:
    build:
      args:
        - PHP_BUILD_REDIS=1
    environment:
      XF_CACHE_ENABLE: 1
      XF_CACHE_HOST: cache
    depends_on:
      - cache
    networks:
      - cache

  cache:
    image: redis:${REDIS_VERSION:-7.0}-alpine
    networks:
      - cache
    volumes:
      - cache:/data

networks:
  cache:

volumes:
  cache:
