services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15.3}-alpine
    environment:
      POSTGRES_USER: ${XF_DB_USER}
      POSTGRES_PASSWORD: ${XF_DB_PASSWORD}
      POSTGRES_DB: ${XF_DB_DATABASE}
    volumes:
      - xf-pg:/var/lib/postgresql/data

volumes:
  xf-pg:
