services:
  xf:
    image: xf:${XF_INSTANCE:-xf}
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
        - PHP_VERSION_COMPOSER=${PHP_VERSION_COMPOSER:-2.8}
        - PHP_VERSION_IGBINARY=${PHP_VERSION_IGBINARY:-3.2.16}
        - PHP_VERSION_IMAGICK=${PHP_VERSION_IMAGICK:-3.8.0}
        - PHP_VERSION_REDIS=${PHP_VERSION_REDIS:-6.2.0}
        - PHP_VERSION_XDEBUG=${PHP_VERSION_XDEBUG:-3.4.4}
        - PHP_VERSION_YAML=${PHP_VERSION_YAML:-2.2.4}
        - PHP_BUILD_IMAGICK=${XF_IMAGICK_ENABLE:-0}
        - PHP_INSTALL_FFMPEG=${XF_XFMG_FFMPEG_ENABLE:-0}
    env_file:
      - .env
    networks:
      - nginx
    volumes:
      - xf:/var/www/html

  nginx:
    image: nginx:${NGINX_VERSION:-1.27}-alpine
    depends_on:
      - xf
    networks:
      - nginx
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - xf:/var/www/html:ro

networks:
  nginx:

volumes:
  xf:
