services:
  xf:
    environment:
      XF_DB_REPLICATION: 1
      XF_DB_HOST_READ: mysql-read
      XF_DB_REPLICATION_USER: ${XF_DB_REPLICATION_USER:-xf_replication}
      XF_DB_REPLICATION_PASSWORD: ${XF_DB_REPLICATION_PASSWORD:-password}

  mysql:
    environment:
      MARIADB_REPLICATION_USER: ${XF_DB_REPLICATION_USER:-xf_replication}
      MARIADB_REPLICATION_PASSWORD: ${XF_DB_REPLICATION_PASSWORD:-password}

  mysql-read:
    image: mariadb:${MARIADB_VERSION:-11.8}
    command:
      - mariadbd
      - --server-id=2
      - --log-basename=db
      - --performance-schema=ON
      - --innodb-buffer-pool-size=256M
      - --innodb-log-file-size=64M
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_REPLICATION_USER: ${XF_DB_REPLICATION_USER:-xf_replication}
      MARIADB_REPLICATION_PASSWORD: ${XF_DB_REPLICATION_PASSWORD:-password}
      MARIADB_MASTER_HOST: db
    depends_on:
      - mysql
    networks:
      - mysql
    volumes:
      - mysql-read:/var/lib/mysql

volumes:
  mysql-read:
