services:
  xf:
    networks:
      - nginx

  nginx:
    image: nginx:${NGINX_VERSION:-1.27}-alpine
    depends_on:
      - xf
    networks:
      - nginx
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - xf:/var/www/html:ro

networks:
  nginx:
