services:
  xf:
    image: xf:${XF_INSTANCE:-xf}
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
        - PHP_VERSION_COMPOSER=${PHP_VERSION_COMPOSER:-2.9}
        - PHP_VERSION_IGBINARY=${PHP_VERSION_IGBINARY:-3.2.17RC1}
        - PHP_VERSION_IMAGICK=${PHP_VERSION_IMAGICK:-3.8.1}
        - PHP_VERSION_REDIS=${PHP_VERSION_REDIS:-6.3.0}
        - PHP_VERSION_XDEBUG=${PHP_VERSION_XDEBUG:-3.4.7}
        - PHP_VERSION_YAML=${PHP_VERSION_YAML:-2.3.0}
        - PHP_BUILD_MYSQL=${PHP_BUILD_MYSQL:-0}
        - PHP_BUILD_PGSQL=${PHP_BUILD_PGSQL:-0}
        - PHP_BUILD_REDIS=${PHP_BUILD_REDIS:-0}
        - PHP_BUILD_SQLSRV=${PHP_BUILD_SQLSRV:-0}
        - PHP_BUILD_IMAGICK=${XF_IMAGICK_ENABLE:-0}
        - PHP_INSTALL_FFMPEG=${XF_XFMG_FFMPEG_ENABLE:-0}
    env_file:
      - .env
    volumes:
      - xf:/var/www/html

volumes:
  xf:
