services:
  xf:
    build:
      args:
        - PHP_BUILD_REDIS=1
    environment:
      XF_CACHE_ENABLE: 1
      XF_CACHE_HOST: redis
    depends_on:
      - redis
    networks:
      - redis

  redis:
    image: redis:${REDIS_VERSION:-8.0}-alpine
    networks:
      - redis
    volumes:
      - redis:/data

networks:
  redis:

volumes:
  redis:
