services:
  xf:
    environment:
      XF_XFES_SEARCH_HOST: elasticsearch
      XF_XFES_SEARCH_USER: ${XF_XFES_SEARCH_USER:-xf}
      XF_XFES_SEARCH_PASSWORD: ${XF_XFES_SEARCH_PASSWORD:-password}
      XF_XFES_SEARCH_INDEX: xf
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-9.1.0}
    environment:
      discovery.type: single-node
      ELASTIC_USERNAME: ${XF_XFES_SEARCH_USER:-xf}
      ELASTIC_PASSWORD: ${XF_XFES_SEARCH_PASSWORD:-password}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

networks:
  elasticsearch:

volumes:
  elasticsearch:
