services:
  xf:
    build:
      target: development
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal}
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
    volumes:
      - .:/var/www/html
      - ./src/config.docker.php:/var/www/html/src/config.php:ro

  nginx:
    ports:
      - 80
    labels:
        - dev.orbstack.domains=${XF_INSTANCE:-}.xf.local
    volumes:
      - .:/var/www/html:ro
