services:
  xf:
    build:
      target: development
    volumes:
      - .:/var/www/html
      - ./src/config.docker.php:/var/www/html/src/config.php:ro

  web:
    volumes:
      - .:/var/www/html:ro
