services:
  xf:
    image: xf:${XF_VERSION:-latest}
    build:
      context: .
      args:
        - PHP_VARIANT=${PHP_VARIANT:-fpm}
        - PHP_VERSION=${PHP_VERSION:-8.2}
        - PHP_VERSION_COMPOSER=${PHP_VERSION_COMPOSER:-2.5}
        - PHP_VERSION_IGBINARY=${PHP_VERSION_IGBINARY:-3.2.14}
        - PHP_VERSION_IMAGICK=${PHP_VERSION_IMAGICK:-3.7.0}
        - PHP_VERSION_REDIS=${PHP_VERSION_REDIS:-5.3.7}
        - PHP_VERSION_XDEBUG=${PHP_VERSION_XDEBUG:-3.2.1}
        - PHP_VERSION_YAML=${PHP_VERSION_YAML:-2.2.3}
        - PHP_BUILD_IMAGICK=${XF_IMAGICK_ENABLE:-0}
        - PHP_INSTALL_FFMPEG=${XF_XFMG_FFMPEG_ENABLE:-0}
    environment:
      XF_DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web
      - db
    volumes:
      - xf:/var/www/html

  web:
    image: nginx:${NGINX_VERSION:-1.25}
    ports:
      - ${XF_PORT:-80}:80
    depends_on:
      - xf
    networks:
      - web
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - xf:/var/www/html:ro

  db:
    image: mariadb:${MARIADB_VERSION:-10.11}
    environment:
      MYSQL_USER: ${XF_DB_USER}
      MYSQL_PASSWORD: ${XF_DB_PASSWORD}
      MYSQL_DATABASE: ${XF_DB_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - db
    volumes:
      - db:/var/lib/mysql

networks:
  web:
  db:

volumes:
  xf:
  db:
