services:
  xf:
    depends_on:
      - search

  search:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-7.17.10}
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - xf-search:/usr/share/elasticsearch/data

volumes:
  xf-search:
