services:
  xf:
    build:
      target: development
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal}
      - XDEBUG_MODE=off
    volumes:
      - .:/var/www/html
      - ./src/config.docker.php:/var/www/html/src/config.php:ro

  web:
    volumes:
      - .:/var/www/html:ro
