services:
  xf:
    environment:
      XF_MAIL_ENABLE: 1
      XF_MAIL_HOST: mailpit
      XF_MAIL_PORT: 1025
      XF_MAIL_SSL: 0
      XF_MAIL_USERNAME: ${XF_MAIL_USERNAME:-xf}
      XF_MAIL_PASSWORD: ${XF_MAIL_PASSWORD:-password}
    depends_on:
      - mailpit
    networks:
      - mailpit

  mailpit:
    image: axllent/mailpit:v${MAILPIT_VERSION:-1.29}
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH: ${XF_MAIL_USERNAME:-xf}:${XF_MAIL_PASSWORD:-password}
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    ports:
      - "8025"
    labels:
        - dev.orbstack.domains=mail.${XF_INSTANCE:-}.xf.local
    networks:
      - mailpit
    volumes:
      - mailpit:/data

networks:
  mailpit:

volumes:
  mailpit:
