services:
  xf:
    build:
      args:
        - PHP_BUILD_PGSQL=1
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    image: postgres:${POSTGRES_VERSION:-18.3}-alpine
    environment:
      POSTGRES_USER: ${XF_DB_USER:-xf}
      POSTGRES_PASSWORD: ${XF_DB_PASSWORD:-password}
      POSTGRES_DB: ${XF_DB_DATABASE:-xf}
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  postgres:

volumes:
  postgres:
