name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - "**.go"
      - .golangci.yml

  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - .golangci.yml

concurrency:
  group: "${{ github.workflow }}@${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          version: v2.11

  test:
    name: ${{ matrix.name }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - name: Test
            command: make test
          - name: Test (race)
            command: make test-race
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: stable

      - name: ${{ matrix.name }}
        env:
          COMMAND: ${{ matrix.command }}
        run: ${COMMAND}

  test-coverage:
    name: Test (coverage)
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: stable

      - name: Test coverage
        run: make test-coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
