name: Clean images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * WED"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

env:
  PACKAGE: php-ci

jobs:
  clean-images:
    name: Clean images
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      packages: write # required to clean old images

    steps:
      - name: Delete old versions
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-type: container
          package-name: ${{ env.PACKAGE }}
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
