name: Clean images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * WED"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  PACKAGE: php-ci

jobs:
  clean-images:
    name: Clean images
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Delete old versions
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name: ${{ env.PACKAGE }}
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
