name: Go modules

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - go.mod
      - go.sum

  pull_request:
    branches:
      - "main"
    paths:
      - go.mod
      - go.sum

concurrency:
  group: "${{ github.workflow }}@${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

permissions: {}

jobs:
  go-mod:
    name: Go modules
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable

      - name: Go modules
        run: make mod-tidy-diff
