name: Go modules

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - go.mod
      - go.sum

  pull_request:
    branches:
      - "main"
    paths:
      - go.mod
      - go.sum

concurrency:
  group: "${{ github.workflow }}@${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

permissions: {}

jobs:
  go-mod:
    name: Go modules
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: Go modules
        run: make mod-tidy-diff
