name: Publish CI images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * TUE"

  push:
    branches:
      - 'main'
    paths:
      - 'instance/Dockerfile'

  pull_request:
    branches:
      - 'main'
    paths:
      - 'instance/Dockerfile'

concurrency:
  group: "${{ github.workflow }}@${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  IMAGE: php-ci
  IMAGE_DESCRIPTION: A PHP build for XenForo CI
  IMAGE_TARGET: ci
  IMAGE_PHP_VARIANT: cli
  IMAGE_LATEST_VERSION: 8.2
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: ${{ github.repository_owner }}

jobs:
  publish-ci:
    name: Publish CI images
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php-version: ['7.2', '8.1', '8.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && matrix.php-version == env.IMAGE_LATEST_VERSION }}
            type=raw,value=${{ matrix.php-version }}

      - name: Log in to the registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: instance
          target: ${{ env.IMAGE_TARGET }}
          build-args: |
            PHP_VARIANT=${{ env.IMAGE_PHP_VARIANT }}
            PHP_VERSION=${{ matrix.php-version }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          provenance: false
          cache-from: type=gha,scope=${{ github.ref_name }}-${{ matrix.php-version }}
          cache-to: type=gha,scope=${{ github.ref_name }}-${{ matrix.php-version }},mode=max
          push: ${{ github.event_name != 'pull_request' }}
