name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: "${{ github.workflow }}@${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

permissions: {}

jobs:
  release:
    name: Release
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: write # required to create releases
      id-token: write # required to sign releases
      attestations: write # required to attest releases
      artifact-metadata: write # required to upload release artifacts

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
          cache: false

      - name: Generate changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          version: '2.13'
          args: --verbose --current --strip all
        env:
          OUTPUT: RELEASE.md

      - name: Release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: '~> v2'
          args: release --clean --release-notes <(cat RELEASE.md | tail -n +3)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          MACOS_SIGN_P12: ${{ secrets.MACOS_CERT_P12_BASE64 }}
          MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          MACOS_NOTARY_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY_P8_BASE64 }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}

      - uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-checksums: ./dist/checksums.txt
